apiVersion: v1
kind: Pod
metadata:
  name: complex-app
  labels:
    app: complex-debug
spec:
  containers:
  - name: web-app
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: data-processor
    image: busybox:1.35
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo '<h1>Data processed at $(date)</h1>' > /shared/index.html; sleep 60; done"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared
  volumes:
  - name: shared-data
    emptyDir: {}
