apiVersion: v1
kind: Pod
metadata:
  name: problematic-app
  labels:
    app: debug-demo-problem
spec:
  containers:
  - name: app-container
    image: busybox:1.35
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'App running...'; sleep 30; done"]
    env:
    - name: DEBUG_MODE
      value: "true"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
