apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug
    image: busybox:1.35
    command: ["sleep", "3600"]

    envFrom:
    - configMapRef:
        name: app-config

    env:
    - name: SECRET_API
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: api_key

    volumeMounts:
    - name: cm-vol
      mountPath: /config
    - name: sec-vol
      mountPath: /secrets
      readOnly: true

  volumes:
  - name: cm-vol
    configMap:
      name: app-config-yaml
  - name: sec-vol
    secret:
      secretName: app-secrets-yaml
