apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-test
  labels:
    app: final-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-test
  template:
    metadata:
      labels:
        app: final-test
    spec:
      containers:
      - name: test-container
        image: nginx:1.21
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
