apiVersion: v1
kind: Pod
metadata:
  name: multi-container-app
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}
  - name: config-volume
    emptyDir: {}

  initContainers:
  - name: config-setup
    image: busybox
    command: ["sh","-c"]
    args:
      - |
        echo "server_name=web-app" > /config/app.conf
        echo "log_level=info" >> /config/app.conf
        echo "port=80" >> /config/app.conf
    volumeMounts:
    - name: config-volume
      mountPath: /config

  containers:
  - name: web-app
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    - name: config-volume
      mountPath: /etc/app-config
    command: ["sh","-c"]
    args:
      - |
        cat /etc/app-config/app.conf
        nginx -g 'daemon off;'

  - name: log-sidecar
    image: busybox
    command: ["sh","-c"]
    args:
      - |
        while true; do
          echo "=== LOG WATCH ==="
          tail -n 5 /var/log/nginx/access.log 2>/dev/null || echo "No logs yet"
          sleep 5
        done
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
