apiVersion: v1
kind: Pod
metadata:
  name: fixed-pod
spec:
  containers:
  - name: fixed-container
    image: nginx:1.21
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
