apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: production
  annotations:
    description: "Updated quota for production workloads, allows moderate scaling"
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "50"
